define(['dojo/_base/declare', 'jimu/BaseWidget', 'jimu/dijit/Report', 'jimu/dijit/PageUtils'],
function(declare, BaseWidget, Report, PageUtils) {
  //To create a widget, you need to derive from BaseWidget.
  return declare([BaseWidget], {
    // DemoWidget code goes here

    //please note that this property is be set by the framework when widget is loaded.
    //templateString: template,

    baseClass: 'jimu-widget-report',

    postCreate: function() {
      this.inherited(arguments);
      console.log('postCreate');
    },

	startup: function() {
      this.inherited(arguments);
      
	  this.report = new Report({
            footNotes: "Report Generated by Artemis",
            printTaskUrl: "http://utility.arcgisonline.com/arcgis/rest/services/Utilities/PrintingTools/GPServer/Export%20Web%20Map%20Task",
            reportLayout: {
              "pageSize": PageUtils.PageSizes.A4,
              "orientation": PageUtils.Orientation.Landscape
            }
          });
		  
      console.log('startup');
   },
    onOpen: function(){
      console.log('onOpen');
    },

    onClose: function(){
      console.log('onClose');
    },

    onMinimize: function(){
      console.log('onMinimize');
    },

    onMaximize: function(){
      console.log('onMaximize');
    },

    onSignIn: function(credential){
      /* jshint unused:false*/
      console.log('onSignIn');
    },

    onSignOut: function(){
      console.log('onSignOut');
    },

    showVertexCount: function(count){
      this.vertexCount.innerHTML = 'The vertex count is: ' + count;
    },
    
	_onBtnPrintClicked: function(){
		var printData = [
		{
		  addPageBreak: true,
		  type: "map",
		  map: this.map
		},
		{		
		  title: "List of parks",
		  addPageBreak: false,
		  type: "table",
		  tableCols: 3,
		  data: {
			showRowIndex: false,
			rows:  [["Brookside Park", "1630 Brookside Avenue, Redlands, CA 92373", "34.045347, -117.209909"],
			        ["Crafton Park", "Wabash Ave & Independence Ave, Redlands, CA 92374", "34.060946, -117.140118"],
					["Ford Park", "Parkford Dr & Redlands Blvd, Redlands, CA 92374", "34.043828, -117.160692"],
					["Prospect Park", "352 Prospect Dr., Redlands, CA 92373", "34.039145, -117.172582"],
					["Sylvan Park", "601 N University St, Redlands, CA 92374", "34.059977, -117.168179"]],
			cols: ["Name", "Address", "Lat/Lon"]
		  }
		},
		{
			title: "Photos",
			type: "html",
			data: '<div style="height: 450px;"><div style="width: 250px; margin-left: 10px; float: left;"><div><img style="width: 250px; height: 200px; float: left;" src="https://static.pexels.com/photos/38136/pexels-photo-38136.jpeg" /></div><div style="text-align:center; margin-bottom: 10px;">Brookside Park</div></div>'+
			      '<div style="width: 250px; margin-left: 10px; float: left;"><div><img style="width: 250px; height: 200px; float: left;" src="https://static1.squarespace.com/static/556a1885e4b0bdc6f0794659/t/577a8e0cebbd1a47dbec29ed/1467649577049/AdobeStock_27621934+%281%29.jpeg" /></div><div style="text-align:center; margin-bottom: 10px;">Crafton Park</div></div>'+
				  '<div style="width: 250px; margin-left: 10px; float: left;"><div><img style="width: 250px; height: 200px; float: left;" src="https://cdn.pixabay.com/photo/2014/02/23/02/56/forest-272595_960_720.jpg" /></div><div style="text-align:center; margin-bottom: 10px;">Ford Park</div></div>'+
				  '<div style="width: 250px; margin-left: 10px; float: left; clear:left;"><div><img style="width: 250px; height: 200px; float: left;" src="https://media0.giphy.com/media/lwoYSJLAsABBm/200_s.gif" /></div><div style="text-align:center; margin-bottom: 10px;">Prospect Park</div></div>'+
				  '<div style="width: 250px; margin-left: 10px; float: left;"><div><img style="width: 250px; height: 200px; float: left;" src="http://images.clipartpanda.com/forest-clipart-forest-wallpaper-1.jpg" /></div><div style="text-align:center; margin-bottom: 10px;">Sylvan Park</div></div></div>'
		}];
        this.report.print("Redlands Parks", printData);
      },
	    
  });
});